---
- name: Migrating the Swarmguard agent from NodeJS to the Go version
  hosts: all

  tasks:
    - name: "Updating the repositories and upgrading them"
      apt: state=latest force_apt_get=yes
      
    - name: "Creating an empty file"
      file:
        path: "/home/pi/test.txt"
        state: touch
      become: yes
