---
- name: Migrating the Swarmguard agent from NodeJS to the Go version
  hosts: all

  tasks:
    - name: Update apt packages
      become: yes
      ignore_errors: true
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Upgrade apt packages
      become: yes
      ignore_errors: true
      apt:
        upgrade: yes
      
    - name: "Create an empty file"
      file:
        path: "/home/pi/test.txt"
        state: touch
      become: yes

    - ansible.builtin.shell: "uname -m"
      register: os_information

    - name: "Print the OS versions"
      local_action: ansible.builtin.debug var={{ item }}
      become: yes
      with_items: 
        - os_information.stdout_lines
      
    - debug: msg?"

