---
- name: Migrating the Swarmguard agent from NodeJS to the Go version
  hosts: all

  tasks:
    - name: Update apt packages
      become: yes
      ignore_errors: true
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Upgrade apt packages
      become: yes
      ignore_errors: true
      apt:
        upgrade: yes
      
    - name: "Create an empty file"
      file:
        path: "/home/pi/test.txt"
        state: touch
      become: yes

    - ansible.builtin.shell: "uname -m"
      register: os_information
      ignore_errors: true

    - debug:
        var: os_information.stdout

    - ansible.builtin.shell: "reboot"
      become: yes
      ignore_errors: true
      ignore_unreachable: true

    - name: Pause for 2 minutes
      ansible.builtin.pause:
        minutes: 2

    - name: Ping the local devices
      ping:
      register: ping_result
      ignore_errors: true

    - debug:
        var: ping_result.stdout

    - name: Ping the other SwarmGuard-Agents
      shell: ping -c 5 -w 10 -n 10 kunbus0.swarm
      register: ping_swarm
      ignore_errors: true
      ignore_unreachable: true

    - debug:
        var: ping_swarm.stdout


      
      

