---
- name: Migrating the Swarmguard agent from NodeJS to the Go version
  hosts: all

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      ignore_errors: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      
    - name: "Creating an empty file"
      file:
        path: "/home/pi/test.txt"
        state: touch
      become: yes
