---
- name: Installing basic firmware and libraries for the proxy server!
  hosts: all

  tasks:
    - name: "Update the repositories and upgrade them (apt-get update + apt-get upgrade)"
      apt: state=latest force_apt_get=yes
      
    - name: "Creating an empty file"
      file:
        path: "/home/pi/test.txt"
        state: touch
      become: yes
